server:
  port: 7001

eureka:
  instance:
    # eureka服务端的实例名字，模拟集群在【C:\Windows\System32\drivers\etc\hosts】中配置
    hostname: eureka7001.com
  client:
    # 表示不向注册中心注册自己
    register-with-eureka: false
    # 表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址。集群，相互注册
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    # 立即关闭，服务心跳不可达立即删除
    enable-self-preservation: false
    # 服务刷新时间，单位：毫秒
    eviction-interval-timer-in-ms: 2000
