server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          enabled: true
      routes:
        # 路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh
          # 匹配后提供服务的路由地址
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          # 断言,路径相匹配的进行路由 localhost:9527/payment/get/**
          predicates:
            - Path=/payment/get/**

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      # 是否将自己注册进EurekaServer，默认为true
      register-with-eureka: true
      # 表示是否从 Eureka Server 获取注册的服务信息
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


